### ISSUE TITLE
ymlファイルにgatewayが必要では？

### ISSUE THREAD

**Issue by kekke-gk** [project-hatohol/test-environment-manager#29]
\# ./start_clone_setup.py sample.yml
を実行すると、以下のようなエラーになります。

そしてsample.yml内のコンテナそれぞれに
gateway: 10.0.3.1
を追記するとエラーがなくなりました。

ymlファイルにgatewayが必要ではないでしょうか。

以下エラー内容

---------------------
Install config files: zabbix-server20-sample
Traceback (most recent call last):
File "./start_clone_setup.py", line 14, in
setup.start_setup_containers(argvs[1])
File "/home/keisuke/git/test-environment-manager/clone_config/setup.py", line 440, in start_setup_containers
install_containers_config(list_of_container_info)
File "/home/keisuke/git/test-environment-manager/clone_config/setup.py", line 430, in install_containers_config
install_container_config(container_name, container_info)
File "/home/keisuke/git/test-environment-manager/clone_config/setup.py", line 423, in install_container_config
install_container_config_file(container_info)
File "/home/keisuke/git/test-environment-manager/clone_config/setup.py", line 366, in install_container_config_file
IPV4_GATEWAY_SETTING_KEY + container_info['gateway'] + '\n'
KeyError: 'gateway'

**Comment by Mnakagawa** [comment]
That's right!
これはsample.ymlに更新がかかっていないためです。
正しくclone_setup.pyが通るsample.ymlファイルを作ってプルリクエストを出してみてください。

**Comment by kekke-gk** [comment]
はい、わかりました！

**Comment by bynnchapu** [comment]
マージされたので、クローズしますね。
